spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: system
              uri: lb://example-platform-system
              predicates:
                - Path=/system/**
              filters:
                - StripPrefix=1
