spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
knife4j:
  gateway:
    enabled: true
    strategy: DISCOVER
    discover:
      enabled: true
      oas3:
        url: /v3/api-docs
