<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me</groupId>
        <artifactId>me-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>me-shared</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>me-shared-log</module>
        <module>me-shared-core</module>
        <module>me-shared-web</module>
        <module>me-shared-mybatisplus</module>
        <module>me-shared-processor</module>
    </modules>
</project>
