server:
  port: 8079

spring:
  main:
    banner-mode: off
  application:
    name: example-platform-system
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: dev
      discovery:
        namespace: dev
  config:
    import:
      - application-spring.yml
      - nacos:example-platform-common.yml
      - nacos:example-platform-system.yml
