volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Password@123
    volumes:
      - mysql_data:/var/lib/mysql/
      - ./mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    command:
      [ "redis-server", "--requirepass", "Password@123" ]
