server:
  port: 8080

spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://pi-aqm-auth:8030
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: management
              uri: http://pi-aqm-management:8030
              predicates:
                - Path=/management/**
              filters:
                - StripPrefix=1
            - id: file
              uri: http://pi-aqm-file:8030
              predicates:
                - Path=/file/**
              filters:
                - StripPrefix=1

knife4j:
  gateway:
    enabled: ${DOC_ENABLED:false}
    routes:
      - name: auth
        url: /auth/v3/api-docs
      - name: management
        url: /management/v3/api-docs
      - name: file
        url: /file/v3/api-docs
